# Site settings
title: Yuri Cuervo
twitter_username: 
name: Yuri Cuervo

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ycuervo
 - title: LinkedIn
   url: https://www.linkedin.com/in/ycuervo/

#Intro
intro:
   I am a Manager of Software Development working at Entertainment Partners. I started my career at Entertainment Partners as an Administrative Assistant / Programmer Level 1 and over the course of my career move into a Programmer, a Senior, a Technicall Lead and now Development Manager.<br/><br/>
   I enjoy working with great people who are motivated by a challenge and always keep a positive outlook on work and life. I keep a high emphasis on good development practices, automation and always learning.

#Any buzzword skills you want to include
skills:
 - Java
 - Spring
 - SQL
 - Git
 - Jenkins
 - SOLID Principles
 - Design Patterns

#Work experience is required
roles:
 - title: Manager Software Development
   start: 2017
   end: Ongoing
   employer: Entertainment Partners
   description: As a Manager Software Development, directly manage software development teams. Manage expectations of personnel, stake holders and business. Oversee coding standards and SDLC practices.
 - title: Associate Manager Software Development
   start: 2016
   end: 2011
   employer: Entertainment Partners
   description: As Associate Manager, Software Development, directly manage software development teams. Manage expectations of personnel, stake holders and business. Oversee coding standards and SDLC practices.
 - title: Senior Software Developer - Technical Lead
   start: 2011
   end: 2016
   employer: Entertainment Partners
   description: As a Senior Software Developer and Technical Lead, take part in the analysis, design and implementation of new applications. Enforce coding standards and best practices. Implement procedures and work flows to facilitate SDLC and ensure delivery of applications.
 - title: Senior Software Developer
   start: 2008
   end: 2011
   employer: Entertainment Partners
   description: As a Senior Software Developer, take part in the analysis, design and implementation of new applications.
 - title: Senior Programmer Analyst
   start: 2000
   end: 2008
   employer: Entertainment Partners
   description: As a Senior Programmer Analyst, take part in the analysis, design and implementation of new applications.
 - title: Programmer Analyst
   start: 1997
   end: 2000
   employer: Entertainment Partners
   description: As a Programmer Analyst, take part in the analysis, design and implementation of new applications.

#Education is required
education:
 - level: Associate's Degree
   date: 1998
   subject: Computer Science
   school: Los Angeles Valley College

#List of interesting Github repo/projects to include - optional
github:
 - /ycuervo/media-org

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo:
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. In my current role Java is the primary language used - and I am familiar with many of the languages features. <br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Ant and Jenkins.<br/><br/>
   <strong>Web Development</strong>: The majority of my Web Development knowledge has come from side jobs here and there creating sites. A few years ago, I built a site for a friend who runs a non-profit <a target='_blank' href="http://50thstreetyouthprogram.org">50th Street Youth Program</a>. This site was written in PHP backed by a mysql DB.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Linux, Python, JavaScript, some Android. <br/><br/>
